
name: Run Selenium On GitHub Action
on:
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Selenium
        run: pip install selenium

      - name: FIRE UP THE GRID CANNON!!!
        run: docker-compose -f docker-compose.yaml up -d

      #- name: RUN THE GRID!!!
        #run: java -jar selenium-server-4.8.1.jar standalone

      - name: Running the Python file
        run: python3 Selenium_Website_Test.py

      - name: KILL THE GRID!!!!
        run: docker-compose -f docker-compose.yaml down

      - name: TEAM ROCKET!!!!
        run: ./TeamRocket.sh

      - name: The Legend Never Dies
        run: ./TheLegendNeverDies.sh
