
name: Run Selenium On GitHub Action
on:
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install Selenium
        run: pip install selenium

      #- name: Install Jq
     #   run: sudo apt-get install jq

      - name: FIRE UP THE GRID CANNON!!!
        run: docker-compose -f docker-compose.yaml up -d

      - name: Wait for grid
        run: ./wait-for-grid.sh

     # - name: Running the Python file
       # run: |
         # netstat -planet | grep 4444
         # netstat -planet
         # python3  Selenium_Website_Test.py
      
      - name: Running the Python file
        run: python3  Selenium_Website_Test.py

      - name: KILL THE GRID!!!!
        run: docker-compose -f docker-compose.yaml down

      - name: TEAM ROCKET!!!!
        run: ./TeamRocket.sh

      - name: The Legend Never Dies
        run: ./TheLegendNeverDies.sh
